<?php

namespace Database\Seeders;

use App\Models\Vivienda;
use Illuminate\Database\Seeder;

class ViviendaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $viviendas = [
            [
                'codigo' => 'VIV-2024-0001',
                'direccion' => 'Av. 3 de Abril 1500',
                'barrio' => 'Centro',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 65.50,
                'superficie_terreno' => 250.00,
                'cantidad_ambientes' => 3,
                'propietario_actual' => 'Roberto Gómez',
                'telefono_contacto' => '3794123456',
            ],
            [
                'codigo' => 'VIV-2024-0002',
                'direccion' => 'Av. Maipú 2350',
                'barrio' => 'San Benito',
                'tipo_vivienda' => 'proxima_entrega',
                'superficie_cubierta' => 72.00,
                'superficie_terreno' => 300.00,
                'cantidad_ambientes' => 4,
            ],
            [
                'codigo' => 'VIV-2024-0003',
                'direccion' => 'Calle Junín 890',
                'barrio' => 'Yapeyú',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 58.00,
                'superficie_terreno' => 200.00,
                'cantidad_ambientes' => 2,
                'propietario_actual' => 'Ana María López',
                'telefono_contacto' => '3794234567',
            ],
            [
                'codigo' => 'VIV-2024-0004',
                'direccion' => 'Av. Libertad 1234',
                'barrio' => 'Laguna Brava',
                'tipo_vivienda' => 'recuperada',
                'superficie_cubierta' => 68.00,
                'superficie_terreno' => 280.00,
                'cantidad_ambientes' => 3,
            ],
            [
                'codigo' => 'VIV-2024-0005',
                'direccion' => 'Calle Córdoba 567',
                'barrio' => 'Berón de Astrada',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 75.00,
                'superficie_terreno' => 320.00,
                'cantidad_ambientes' => 4,
                'propietario_actual' => 'Carlos Fernández',
                'telefono_contacto' => '3794345678',
            ],
            [
                'codigo' => 'VIV-2024-0006',
                'direccion' => 'Av. Costanera 890',
                'barrio' => 'Arazaty',
                'tipo_vivienda' => 'proxima_entrega',
                'superficie_cubierta' => 62.00,
                'superficie_terreno' => 240.00,
                'cantidad_ambientes' => 3,
            ],
            [
                'codigo' => 'VIV-2024-0007',
                'direccion' => 'Calle San Martín 1456',
                'barrio' => 'Quilmes',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 70.00,
                'superficie_terreno' => 290.00,
                'cantidad_ambientes' => 3,
                'propietario_actual' => 'Marta Rodríguez',
                'telefono_contacto' => '3794456789',
            ],
            [
                'codigo' => 'VIV-2024-0008',
                'direccion' => 'Av. Independencia 2100',
                'barrio' => 'Molina Punta',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 64.00,
                'superficie_terreno' => 260.00,
                'cantidad_ambientes' => 3,
                'propietario_actual' => 'Jorge Martínez',
                'telefono_contacto' => '3794567890',
            ],
            [
                'codigo' => 'VIV-2024-0009',
                'direccion' => 'Calle Belgrano 789',
                'barrio' => 'Pirayuí',
                'tipo_vivienda' => 'proxima_entrega',
                'superficie_cubierta' => 68.50,
                'superficie_terreno' => 275.00,
                'cantidad_ambientes' => 3,
            ],
            [
                'codigo' => 'VIV-2024-0010',
                'direccion' => 'Av. Ferré 1890',
                'barrio' => 'Güemes',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 71.00,
                'superficie_terreno' => 295.00,
                'cantidad_ambientes' => 4,
                'propietario_actual' => 'Laura Sánchez',
                'telefono_contacto' => '3794678901',
            ],
            [
                'codigo' => 'VIV-2024-0011',
                'direccion' => 'Calle Salta 456',
                'barrio' => 'Aldana',
                'tipo_vivienda' => 'recuperada',
                'superficie_cubierta' => 60.00,
                'superficie_terreno' => 230.00,
                'cantidad_ambientes' => 2,
            ],
            [
                'codigo' => 'VIV-2024-0012',
                'direccion' => 'Av. Pujol 2345',
                'barrio' => 'Perichón',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 73.00,
                'superficie_terreno' => 305.00,
                'cantidad_ambientes' => 4,
                'propietario_actual' => 'Pedro Ramírez',
                'telefono_contacto' => '3794789012',
            ],
            [
                'codigo' => 'VIV-2024-0013',
                'direccion' => 'Calle Tucumán 1123',
                'barrio' => 'Lomas',
                'tipo_vivienda' => 'proxima_entrega',
                'superficie_cubierta' => 66.00,
                'superficie_terreno' => 270.00,
                'cantidad_ambientes' => 3,
            ],
            [
                'codigo' => 'VIV-2024-0014',
                'direccion' => 'Av. Raúl Alfonsín 890',
                'barrio' => 'Esperanza',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 69.00,
                'superficie_terreno' => 285.00,
                'cantidad_ambientes' => 3,
                'propietario_actual' => 'Silvia Torres',
                'telefono_contacto' => '3794890123',
            ],
            [
                'codigo' => 'VIV-2024-0015',
                'direccion' => 'Calle Mendoza 567',
                'barrio' => 'Libertad',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 67.50,
                'superficie_terreno' => 278.00,
                'cantidad_ambientes' => 3,
                'propietario_actual' => 'Ricardo Benítez',
                'telefono_contacto' => '3794901234',
            ],
            [
                'codigo' => 'VIV-2024-0016',
                'direccion' => 'Av. Artigas 1678',
                'barrio' => 'Laguna Seca',
                'tipo_vivienda' => 'proxima_entrega',
                'superficie_cubierta' => 74.00,
                'superficie_terreno' => 310.00,
                'cantidad_ambientes' => 4,
            ],
            [
                'codigo' => 'VIV-2024-0017',
                'direccion' => 'Calle Entre Ríos 234',
                'barrio' => 'San Gerónimo',
                'tipo_vivienda' => 'recuperada',
                'superficie_cubierta' => 61.00,
                'superficie_terreno' => 235.00,
                'cantidad_ambientes' => 2,
            ],
            [
                'codigo' => 'VIV-2024-0018',
                'direccion' => 'Av. Teniente Ibáñez 2456',
                'barrio' => 'Quinta Ferré',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 70.50,
                'superficie_terreno' => 292.00,
                'cantidad_ambientes' => 4,
                'propietario_actual' => 'Gabriela Acosta',
                'telefono_contacto' => '3794012345',
            ],
            [
                'codigo' => 'VIV-2024-0019',
                'direccion' => 'Calle La Rioja 890',
                'barrio' => 'Camba Cuá',
                'tipo_vivienda' => 'entregada',
                'superficie_cubierta' => 65.00,
                'superficie_terreno' => 265.00,
                'cantidad_ambientes' => 3,
                'propietario_actual' => 'Héctor Romero',
                'telefono_contacto' => '3794123450',
            ],
            [
                'codigo' => 'VIV-2024-0020',
                'direccion' => 'Av. Chacabuco 1567',
                'barrio' => 'Riachuelo',
                'tipo_vivienda' => 'proxima_entrega',
                'superficie_cubierta' => 72.50,
                'superficie_terreno' => 300.00,
                'cantidad_ambientes' => 4,
            ],
        ];

        foreach ($viviendas as $vivienda) {
            Vivienda::create($vivienda);
        }
    }
}
